{
  "_id": ObjectId("5944113870d1e20a7f41dd13"),
  "updatedAt": ISODate("2017-06-16T17:11:20.927Z"),
  "createdAt": ISODate("2017-06-16T17:11:20.927Z"),
  "stripeCharge": {
    "transfer_group": null,
    "status": "succeeded",
    "statement_descriptor": null,
    "source_transfer": null,
    "source": {
      "tokenization_method": null,
      "name": "rest@test.com",
      "last4": "4242",
      "funding": "credit",
      "fingerprint": "3VzKr8O2Xkz9hxBh",
      "exp_year": 2018,
      "exp_month": 1,
      "dynamic_last4": null,
      "cvc_check": "pass",
      "customer": null,
      "country": "US",
      "brand": "Visa",
      "address_zip_check": null,
      "address_zip": null,
      "address_state": null,
      "address_line2": null,
      "address_line1_check": null,
      "address_line1": null,
      "address_country": null,
      "address_city": null,
      "object": "card",
      "id": "card_1AVNybAOW0NF1YafU48Ws2gb"
    },
    "shipping": null,
    "review": null,
    "refunds": {
      "url": "/v1/charges/ch_1AVNyeAOW0NF1YafKq8Nh4Z5/refunds",
      "total_count": 0,
      "has_more": false,
      "data": [],
      "object": "list"
    },
    "refunded": false,
    "receipt_number": null,
    "receipt_email": null,
    "paid": true,
    "outcome": {
      "type": "authorized",
      "seller_message": "Payment complete.",
      "risk_level": "normal",
      "reason": null,
      "network_status": "approved_by_network"
    },
    "order": null,
    "on_behalf_of": null,
    "livemode": false,
    "invoice": null,
    "failure_message": null,
    "failure_code": null,
    "dispute": null,
    "destination": null,
    "description": "Richard Bell",
    "customer": null,
    "currency": "usd",
    "created": 1497633080,
    "captured": true,
    "balance_transaction": "txn_1AVNyeAOW0NF1Yaf1G5JtacK",
    "application_fee": null,
    "application": null,
    "amount_refunded": 0,
    "amount": 69300,
    "object": "charge",
    "id": "ch_1AVNyeAOW0NF1YafKq8Nh4Z5"
  },
  "cart": [{
    "id": "4004",
    "quantity": 1
  }, {
    "id": "4003",
    "quantity": 1
  }],
  "customer": {
    "firstName": "Richard",
    "lastName": "Bell",
    "email": "richard@ebells.net",
    "streetAddress": "123 state st",
    "cityAddress": "capital",
    "stateAddress": "CA"
  },
  "order": [{
    "Category": {
      "updatedAt": "2017-06-14T18:29:50.863Z",
      "createdAt": "2017-06-14T18:29:50.863Z",
      "name": "Health",
      "id": 32
    },
    "updatedAt": "2017-06-14T18:29:50.817Z",
    "createdAt": "2017-06-14T18:29:50.817Z",
    "quantity": 81,
    "image": "http://lorempixel.com/640/480/fashion",
    "categoryID": 32,
    "price": "310.00",
    "description": "Est qui iste et. Iure est similique optio et libero voluptas in. Rerum veritatis ratione. Dolorem ut dolor temporibus nesciunt aut id. Sit mollitia non reprehenderit sequi aperiam.",
    "SKU": 67110,
    "name": "Small Concrete Chicken",
    "id": 4003
  }, {
    "Category": {
      "updatedAt": "2017-06-14T18:29:50.863Z",
      "createdAt": "2017-06-14T18:29:50.863Z",
      "name": "Electronics",
      "id": 33
    },
    "updatedAt": "2017-06-14T18:29:50.817Z",
    "createdAt": "2017-06-14T18:29:50.817Z",
    "quantity": 73,
    "image": "http://lorempixel.com/640/480/abstract",
    "categoryID": 33,
    "price": "383.00",
    "description": "Qui ut saepe quia. Nesciunt facere earum qui. Sed et et distinctio rerum laborum minus sunt. Voluptas vero ab minima dolores. A eum vero error. Consequuntur ea est eveniet non earum magni aut.",
    "SKU": 62631,
    "name": "Gorgeous Fresh Computer",
    "id": 4004
  }],
  "__v": 0
} {
  "_id": ObjectId("5944117670d1e20a7f41dd14"),
  "updatedAt": ISODate("2017-06-16T17:12:22.562Z"),
  "createdAt": ISODate("2017-06-16T17:12:22.562Z"),
  "stripeCharge": {
    "transfer_group": null,
    "status": "succeeded",
    "statement_descriptor": null,
    "source_transfer": null,
    "source": {
      "tokenization_method": null,
      "name": "jenny@test.com",
      "last4": "4242",
      "funding": "credit",
      "fingerprint": "3VzKr8O2Xkz9hxBh",
      "exp_year": 2018,
      "exp_month": 1,
      "dynamic_last4": null,
      "cvc_check": "pass",
      "customer": null,
      "country": "US",
      "brand": "Visa",
      "address_zip_check": null,
      "address_zip": null,
      "address_state": null,
      "address_line2": null,
      "address_line1_check": null,
      "address_line1": null,
      "address_country": null,
      "address_city": null,
      "object": "card",
      "id": "card_1AVNzbAOW0NF1YafPIj46jkF"
    },
    "shipping": null,
    "review": null,
    "refunds": {
      "url": "/v1/charges/ch_1AVNzeAOW0NF1YafTsnufohS/refunds",
      "total_count": 0,
      "has_more": false,
      "data": [],
      "object": "list"
    },
    "refunded": false,
    "receipt_number": null,
    "receipt_email": null,
    "paid": true,
    "outcome": {
      "type": "authorized",
      "seller_message": "Payment complete.",
      "risk_level": "normal",
      "reason": null,
      "network_status": "approved_by_network"
    },
    "order": null,
    "on_behalf_of": null,
    "livemode": false,
    "invoice": null,
    "failure_message": null,
    "failure_code": null,
    "dispute": null,
    "destination": null,
    "description": "jenny test",
    "customer": null,
    "currency": "usd",
    "created": 1497633142,
    "captured": true,
    "balance_transaction": "txn_1AVNzeAOW0NF1Yafye18VS9h",
    "application_fee": null,
    "application": null,
    "amount_refunded": 0,
    "amount": 45500,
    "object": "charge",
    "id": "ch_1AVNzeAOW0NF1YafTsnufohS"
  },
  "cart": [{
    "id": "4007",
    "quantity": 1
  }, {
    "id": "4002",
    "quantity": 1
  }],
  "customer": {
    "firstName": "jenny",
    "lastName": "test",
    "email": "jenny@test.com",
    "streetAddress": "123 main street",
    "cityAddress": "boondocks",
    "stateAddress": "WA"
  },
  "order": [{
    "Category": {
      "updatedAt": "2017-06-14T18:29:50.863Z",
      "createdAt": "2017-06-14T18:29:50.863Z",
      "name": "Home",
      "id": 37
    },
    "updatedAt": "2017-06-14T18:29:50.817Z",
    "createdAt": "2017-06-14T18:29:50.817Z",
    "quantity": 0,
    "image": "http://lorempixel.com/640/480/abstract",
    "categoryID": 37,
    "price": "376.00",
    "description": "Atque culpa mollitia eum harum. Modi doloremque nostrum facilis quae nihil voluptatem aspernatur incidunt. Omnis quasi sunt culpa.",
    "SKU": 39333,
    "name": "Generic Wooden Tuna",
    "id": 4002
  }, {
    "Category": {
      "updatedAt": "2017-06-14T18:29:50.863Z",
      "createdAt": "2017-06-14T18:29:50.863Z",
      "name": "Home",
      "id": 37
    },
    "updatedAt": "2017-06-14T18:29:50.817Z",
    "createdAt": "2017-06-14T18:29:50.817Z",
    "quantity": 51,
    "image": "http://lorempixel.com/640/480/nature",
    "categoryID": 37,
    "price": "79.00",
    "description": "Quibusdam non architecto itaque consequuntur nulla. Expedita omnis aliquam minus aperiam nesciunt suscipit saepe. Consequatur est et. Voluptate velit totam eveniet sunt molestiae doloremque excepturi odit.",
    "SKU": 52009,
    "name": "Tasty Granite Chips",
    "id": 4007
  }],
  "__v": 0
}
